// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/guide/use-iconfontcn":{"path":"guide/use-iconfontcn","id":"docs/guide/use-iconfontcn","parentId":"DocLayout"},"docs/guide/all-baseline":{"path":"guide/all-baseline","id":"docs/guide/all-baseline","parentId":"DocLayout"},"docs/guide/load-modules":{"path":"guide/load-modules","id":"docs/guide/load-modules","parentId":"DocLayout"},"docs/guide/custom-icon":{"path":"guide/custom-icon","id":"docs/guide/custom-icon","parentId":"DocLayout"},"docs/guide/root-class":{"path":"guide/root-class","id":"docs/guide/root-class","parentId":"DocLayout"},"docs/guide/basic":{"path":"guide/basic","id":"docs/guide/basic","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}},
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/jmr/Documents/GitHub/ireact-material-icons/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/jmr/Documents/GitHub/ireact-material-icons/.dumi/tmp/dumi/theme/ContextWrapper.tsx')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/jmr/Documents/GitHub/ireact-material-icons/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/guide/use-iconfontcn': React.lazy(() => import(/* webpackChunkName: "docs__guide__use-iconfontcn.md" */'/Users/jmr/Documents/GitHub/ireact-material-icons/docs/guide/use-iconfontcn.md')),
'docs/guide/all-baseline': React.lazy(() => import(/* webpackChunkName: "docs__guide__all-baseline.md" */'/Users/jmr/Documents/GitHub/ireact-material-icons/docs/guide/all-baseline.md')),
'docs/guide/load-modules': React.lazy(() => import(/* webpackChunkName: "docs__guide__load-modules.md" */'/Users/jmr/Documents/GitHub/ireact-material-icons/docs/guide/load-modules.md')),
'docs/guide/custom-icon': React.lazy(() => import(/* webpackChunkName: "docs__guide__custom-icon.md" */'/Users/jmr/Documents/GitHub/ireact-material-icons/docs/guide/custom-icon.md')),
'docs/guide/root-class': React.lazy(() => import(/* webpackChunkName: "docs__guide__root-class.md" */'/Users/jmr/Documents/GitHub/ireact-material-icons/docs/guide/root-class.md')),
'docs/guide/basic': React.lazy(() => import(/* webpackChunkName: "docs__guide__basic.md" */'/Users/jmr/Documents/GitHub/ireact-material-icons/docs/guide/basic.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/jmr/Documents/GitHub/ireact-material-icons/docs/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/jmr/Documents/GitHub/ireact-material-icons/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
