// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// @umijs/renderer-*
export {  } from '/Users/jmr/Documents/GitHub/ireact-material-icons/node_modules/@umijs/renderer-react';
export type {  History } from '/Users/jmr/Documents/GitHub/ireact-material-icons/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/jmr/Documents/GitHub/ireact-material-icons/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
export { TestBrowser } from './testBrowser';
// plugins
// plugins types.d.ts
export { defineApp } from './core/defineApp'
export type {  RuntimeConfig } from './core/defineApp'
